sonar.projectKey=Jest-SonarCube
sonar.projectName=Jest-SonarCube
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://legendary-goldfish-g9v7wrr6rj529j9w-9000.app.github.dev
# Pass token via env: 
SONAR_TOKEN=sqp_9a40815c93c9c8ae6b8308652c9140c9b8dea205

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-reporter.xml
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8